version: '3.5'

services:
  mosquitto:
    container_name: mosquitto_container
    image: eclipse-mosquitto:latest
    volumes:
      - ./config:/mosquitto/config/
    ports:
      - "1883:1883"
      - "9001:9001"
      - "8883:8883"
    restart: unless-stopped
    environment:
      - TZ=Africa/Johannesburg
      - PUID=1883
      - PGID=1883
