version: '3.3'

services:
   mysql_wordpress:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
       - ./data/mysql:/etc/mysql/conf.d
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   wordpress:
     depends_on:
       - mysql_wordpress
     image: wordpress:5.8.1-fpm-alpine
     restart: unless-stopped
     environment:
       WORDPRESS_DB_HOST: mysql_wordpress:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
     volumes:
       - wordpress:/var/www/html

   certbot:
     image: certbot/certbot
     restart: unless-stopped
     volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

   nginx:
     depends_on:
       - wordpress
     image: nginx:stable-alpine
     restart: unless-stopped
     volumes:
      - wordpress:/var/www/html
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
     ports:
      - "80:80"
      - "443:443"
     command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

volumes:
    wordpress:
    db_data:
